/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedBuscarRouteImport } from './routes/_authenticated/buscar'
import { Route as AuthenticatedCadastroPlacaRouteImport } from './routes/_authenticated/cadastro.$placa'
import { Route as AuthenticatedCadastroPlacaIndexRouteImport } from './routes/_authenticated/cadastro.$placa.index'
import { Route as AuthenticatedCadastroPlacaSucessoRouteImport } from './routes/_authenticated/cadastro.$placa.sucesso'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBuscarRoute = AuthenticatedBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCadastroPlacaRoute =
  AuthenticatedCadastroPlacaRouteImport.update({
    id: '/cadastro/$placa',
    path: '/cadastro/$placa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastroPlacaIndexRoute =
  AuthenticatedCadastroPlacaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCadastroPlacaRoute,
  } as any)
const AuthenticatedCadastroPlacaSucessoRoute =
  AuthenticatedCadastroPlacaSucessoRouteImport.update({
    id: '/sucesso',
    path: '/sucesso',
    getParentRoute: () => AuthenticatedCadastroPlacaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/cadastro/$placa': typeof AuthenticatedCadastroPlacaRouteWithChildren
  '/cadastro/$placa/sucesso': typeof AuthenticatedCadastroPlacaSucessoRoute
  '/cadastro/$placa/': typeof AuthenticatedCadastroPlacaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/cadastro/$placa/sucesso': typeof AuthenticatedCadastroPlacaSucessoRoute
  '/cadastro/$placa': typeof AuthenticatedCadastroPlacaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/buscar': typeof AuthenticatedBuscarRoute
  '/_authenticated/cadastro/$placa': typeof AuthenticatedCadastroPlacaRouteWithChildren
  '/_authenticated/cadastro/$placa/sucesso': typeof AuthenticatedCadastroPlacaSucessoRoute
  '/_authenticated/cadastro/$placa/': typeof AuthenticatedCadastroPlacaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buscar'
    | '/cadastro/$placa'
    | '/cadastro/$placa/sucesso'
    | '/cadastro/$placa/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buscar'
    | '/cadastro/$placa/sucesso'
    | '/cadastro/$placa'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/buscar'
    | '/_authenticated/cadastro/$placa'
    | '/_authenticated/cadastro/$placa/sucesso'
    | '/_authenticated/cadastro/$placa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/buscar': {
      id: '/_authenticated/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AuthenticatedBuscarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro/$placa': {
      id: '/_authenticated/cadastro/$placa'
      path: '/cadastro/$placa'
      fullPath: '/cadastro/$placa'
      preLoaderRoute: typeof AuthenticatedCadastroPlacaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro/$placa/': {
      id: '/_authenticated/cadastro/$placa/'
      path: '/'
      fullPath: '/cadastro/$placa/'
      preLoaderRoute: typeof AuthenticatedCadastroPlacaIndexRouteImport
      parentRoute: typeof AuthenticatedCadastroPlacaRoute
    }
    '/_authenticated/cadastro/$placa/sucesso': {
      id: '/_authenticated/cadastro/$placa/sucesso'
      path: '/sucesso'
      fullPath: '/cadastro/$placa/sucesso'
      preLoaderRoute: typeof AuthenticatedCadastroPlacaSucessoRouteImport
      parentRoute: typeof AuthenticatedCadastroPlacaRoute
    }
  }
}

interface AuthenticatedCadastroPlacaRouteChildren {
  AuthenticatedCadastroPlacaSucessoRoute: typeof AuthenticatedCadastroPlacaSucessoRoute
  AuthenticatedCadastroPlacaIndexRoute: typeof AuthenticatedCadastroPlacaIndexRoute
}

const AuthenticatedCadastroPlacaRouteChildren: AuthenticatedCadastroPlacaRouteChildren =
  {
    AuthenticatedCadastroPlacaSucessoRoute:
      AuthenticatedCadastroPlacaSucessoRoute,
    AuthenticatedCadastroPlacaIndexRoute: AuthenticatedCadastroPlacaIndexRoute,
  }

const AuthenticatedCadastroPlacaRouteWithChildren =
  AuthenticatedCadastroPlacaRoute._addFileChildren(
    AuthenticatedCadastroPlacaRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBuscarRoute: typeof AuthenticatedBuscarRoute
  AuthenticatedCadastroPlacaRoute: typeof AuthenticatedCadastroPlacaRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBuscarRoute: AuthenticatedBuscarRoute,
  AuthenticatedCadastroPlacaRoute: AuthenticatedCadastroPlacaRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
